version: '3.1'
services:
  php:
    build: ./docker/php-fpm
    working_dir: /var/www/reverse-phone-lookup
    volumes:
      - ./reverse-phone-lookup:/var/www/reverse-phone-lookup

  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./reverse-phone-lookup/public:/var/www/reverse-phone-lookup/public
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
    depends_on:
      - mysql

  node:
    build: ./reverse-phone-lookup
    volumes:
      - ./reverse-phone-lookup:/home/node/app
    environment:
      - NODE_ENV=production
    tty: true
